### ISSUE TITLE
Eclipse Luna 4.4.0, error, haskell platform not yet installed

### ISSUE THREAD

**Issue by hartmut27** [JPMoresmau/eclipsefp#269]
On a fresh install of EclipseFP (2.6.4) on Windows 7 64bit, Eclipse Luna 4.4.0, running Java JDK 8.0.25, while starting the wizard for creating a new Haskell Project I've received the following error message:

The selected wizard could not be started.
Plug-in net.sf.eclipsefp.haskell.ui was unable to load class net.sf.eclipsefp.haskell.ui.wizards.NewHaskellProjectWizard.
An error occurred while automatically activating bundle net.sf.eclipsefp.haskell.ui (1057).

On my system, Haskell platform is *not yet installed*, but I am wondering why the following defensive fix does not seem to detect a missing haskell platform installation -> https://github.com/JPMoresmau/eclipsefp/issues/259

eclipse.buildId=4.4.0.I20140606-1215
java.version=1.8.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.equinox.registry
Error
Wed Feb 04 02:06:39 CET 2015
Plug-in net.sf.eclipsefp.haskell.ui was unable to load class net.sf.eclipsefp.haskell.ui.decorators.ProjectFoldersDecorator.

java.lang.ClassNotFoundException: An error occurred while automatically activating bundle net.sf.eclipsefp.haskell.ui (1057).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:116)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:531)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:311)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:386)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:336)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:328)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:568)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.ui.internal.WorkbenchPlugin$1.run(WorkbenchPlugin.java:294)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:52)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:289)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition$1.run(LightweightDecoratorDefinition.java:125)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.runtime.Platform.run(Platform.java:867)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.internalGetDecorator(LightweightDecoratorDefinition.java:120)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:255)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:83)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:367)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:349)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.ensureResultCached(DecorationScheduler.java:372)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:332)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: org.osgi.framework.BundleException: Exception in net.sf.eclipsefp.haskell.ui.HaskellUIPlugin.start() of bundle net.sf.eclipsefp.haskell.ui.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	... 28 more
Caused by: java.lang.NullPointerException
	at net.sf.eclipsefp.haskell.ui.internal.backend.BackendManager.getToolSandbox(BackendManager.java:1108)
	at net.sf.eclipsefp.haskell.ui.internal.backend.BackendManager.getToolSandboxBin(BackendManager.java:1124)
	at net.sf.eclipsefp.haskell.ui.internal.backend.BackendManager.getExecutablePath(BackendManager.java:128)
	at net.sf.eclipsefp.haskell.ui.internal.backend.BackendManager.start(BackendManager.java:175)
	at net.sf.eclipsefp.haskell.ui.HaskellUIPlugin.start(HaskellUIPlugin.java:106)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	... 35 more

**Comment by JPMoresmau** [comment]
Yes, that NPE is only if no Cabal is found. Installing Cabal somewhere in the path before running should be enough to avoid it.

**Comment by seddon-software** [comment]
I'm trying to get Haskell working and am getting the same error.  I'm new to Haskell and don't know what Cabal is.  I've followed the instructions on installing ghc-7.8.3 (ghc-7.8.4-r0 didn't work at all), but still the error with Eclipse (Luna).  I realise its a pain to get everything to install straight from the instructions, but I suppose I've been spoilt by the PERL, Python, C++, and Scala plugin that work straight away.
I'm not trying to use Haskell on the command line (I've not run the complier yet), just in Eclipse.

**Comment by JPMoresmau** [comment]
You need Cabal, full stop. Cabal is a tool to define and manage project metadata, and download and install libraries. EclipseFP uses Cabal to understand your Haskell projects, get the libraries they depend on, build the projects, etc.

**Comment by seddon-software** [comment]
On 18/03/2015 21:09, JP Moresmau wrote:
>
> You need Cabal, full stop. Cabal is a tool to define and manage 
> project metadata, and download and install libraries. EclipseFP uses 
> Cabal to understand your Haskell projects, get the libraries they 
> depend on, build the projects, etc.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JPMoresmau/eclipsefp/issues/269#issuecomment-83177607>.
>
Thanks for the prompt reply.

Chris Seddon

**Comment by seddon-software** [comment]
Installing Cabal works as suggested.  I can now create Haskell projects and compile them.  However I can't set breakpoints or run the debugger.  Tried quite a few things, but nothing seems to work apart from: the command line debugger is working in the console.  I've set the compiler in preferences, I think I've setup buildwrapper, but a lot of this is guesswork.  I'd of thought this would all be setup during installation or at least documented there.  This doesn't seem very straightforward.

**Comment by seddon-software** [comment]
I seem to have EclipseFP working now on both MacOS and Ubuntu, but there were a couple of confusing issues.  
1) When I press the debug button, I have to look in the console for the debug prompt and I have to control the debug session from there.
2) In the console I type
:break main
main
3) and now things work as expected.  
I can single step the debug the session using function key F5 (not sure why F6 doesn't work).  Expressions seem to wor, but locals don't show up in the variables window.

**Comment by oneumyvakin** [comment]
On Windows Eclipse must be running as administrator.
