### ISSUE TITLE
Very slow typing in 2.6.4 (lag)

### ISSUE THREAD

**Issue by vlatkoB** [JPMoresmau/eclipsefp#274]
Hello,

I was wondering if anyone noticed the lag between typing and displaying typed in editor.
When I say lag, I mean finishing last char and waiting several seconds for that last char appear in editor. Testing files are not large, around 200-300 lines.
It affects only .hs files, .txt editor  works fine, even though file is much larger (over 1K lines).

When I uninstall 2.6.4 and install 2.6.3 (and 2.6.2), the problem is much much less noticeable (but not gone).

Ubuntu 12.04, GHC 7.8.3, BW 0.9

Best regards,
vlatko

**Comment by apriori** [comment]
Similar issue here, any editing operation (even changing a single character) that fires up the editor update loop takes a really long time. Eclipse indicates it mainly gets stuck on syntax highlighting and the editor synchronization (for literally seconds for every single change).

I got an i7-2600k here, so a slow machine can't be the issue :)

Note that EclipseFP was first complaining about the file containing tabs, which I then removed completely. The file in question is around 400 lines long, without includes of extremely big modules (rather small context). 

Please tell me if you need more context information

Environment: 
Arch Linux (latest)
GHC 7.8.4
buildwrapper 0.9.1
EclipseFP 2.6.4
Eclipse Luna 1a (4.4.1) Build id: 20150109-0600

**Comment by JPMoresmau** [comment]
Well, you need to enable buildwrapper debug mode and look at the console output for your project, and check also the Eclipse error log.

**Comment by vlatkoB** [comment]
I enabled BW debug mode, but the output is truncated. For a line of text (inside comment) the BW console for that project gets cleared several times (blinks). I couldn't find where to increase the buffer size.

However, I might have find the culprit. I have `Ansi console` add-on but it is not enabled. When the color pallete was set to `xterm`. I experimented and found that when `Color pallete` is set to `Putty`, it is not so slow anymore. I still see last several chars one by one, but 10-15 of them as before. I uninstalled the add-on, but the speed is the same as with `Putty` pallete.

I couldn't find anything interested in BW console (maybe because it gets truncated/cleared), but in the error log at the end there is `Error while launching buildwrapper process` message.

BW log:

Element seq -> b) -> seq -> [seq]"},{"n":"Data.Sequences.groupBy","t":["Function"],"s":"IsSequence seq =>\n(Element seq -> Element seq -> Bool) -> seq -> [seq]"},{"n":"Data.Sequences.initEx","t":["Fun
ction"],"s":"IsSequence seq => seq -> seq"},{"n":"Data.Sequences.partition","t":["Function"],"s":"IsSequence seq => (Element seq -> Bool) -> seq -> (seq, seq)"},{"n":"Data.Sequences.permutations","t":
["Function"],"s":"IsSequence seq => seq -> [seq]"},{"n":"Data.Sequences.replicate","t":["Function"],"s":"IsSequence seq => Index seq -> Element seq -> seq"},{"n":"Data.Sequences.replicateM","t":["Func
tion"],"s":"IsSequence seq =>\nforall (m :: * -> *).\nMonad m =>\nIndex seq -> m (Element seq) -> m seq"},{"n":"Data.Sequences.span","t":["Function"],"s":"IsSequence seq => (Element seq -> Bool) -> se
q -> (seq, seq)"},{"n":"Data.Sequences.splitAt","t":["Function"],"s":"IsSequence seq => Index seq -> seq -> (seq, seq)"},{"n":"Data.Sequences.subsequences","t":["Function"],"s":"IsSequence seq => seq 
-> [seq]"},{"n":"Data.Sequences.tailEx","t":["Function"],"s":"IsSequence seq => seq -> seq"},{"n":"Data.Sequences.take","t":["Function"],"s":"IsSequence seq => Index seq -> seq -> seq"},{"n":"Data.Seq
uences.takeWhile","t":["Function"],"s":"IsSequence seq => (Element seq -> Bool) -> seq -> seq"},{"n":"Data.Sequences.uncons","t":["Function"],"s":"IsSequence seq => seq -> Maybe (Element seq, seq)"},{
"n":"Data.Sequences.unsafeDrop","t":["Function"],"s":"IsSequence seq => Index seq -> seq -> seq"},{"n":"Data.Sequences.unsafeInit","t":["Function"],"s":"IsSequence seq => seq -> seq"},{"n":"Data.Seque
nces.unsafeSplitAt","t":["Function"],"s":"IsSequence seq => Index seq -> seq -> (seq, seq)"},{"n":"Data.Sequences.unsafeTail","t":["Function"],"s":"IsSequence seq => seq -> seq"},{"n":"Data.Sequences.
unsafeTake","t":["Function"],"s":"IsSequence seq => Index seq -> seq -> seq"},{"n":"Data.Sequences.unsnoc","t":["Function"],"s":"IsSequence seq => seq -> Maybe (seq, Element seq)"},{"n":"Data.Sequence
s.sort","t":["Function"],"s":"OrdSequence seq => seq -> seq"},{"n":"Data.Sequences.cons","t":["Function"],"s":"SemiSequence seq => Element seq -> seq -> seq"},{"n":"Data.Sequences.find","t":["Function
"],"s":"SemiSequence seq =>\n(Element seq -> Bool) -> seq -> Maybe (Element seq)"},{"n":"Data.Sequences.intersperse","t":["Function"],"s":"SemiSequence seq => Element seq -> seq -> seq"},{"n":"Data.Se
quences.reverse","t":["Function"],"s":"SemiSequence seq => seq -> seq"},{"n":"Data.Sequences.snoc","t":["Function"],"s":"SemiSequence seq => seq -> Element seq -> seq"},{"n":"Data.Sequences.sortBy","t
":["Function"],"s":"SemiSequence seq =>\n(Element seq -> Element seq -> Ordering) -> seq -> seq"},{"n":"Data.Sequences.breakLine","t":["Function"],"s":"Textual t => t -> (t, t)"},{"n":"Data.Sequences.
breakWord","t":["Function"],"s":"Textual t => t -> (t, t)"},{"n":"Data.Sequences.lines","t":["Function"],"s":"Textual t => t -> [t]"},{"n":"Data.Sequences.toCaseFold","t":["Function"],"s":"Textual t =
> t -> t"},{"n":"Data.Sequences.toLower","t":["Function"],"s":"Textual t => t -> t"},{"n":"Data.Sequences.toUpper","t":["Function"],"s":"Textual t => t -> t"},{"n":"Data.Sequences.unlines","t":["Funct
ion"],"s":"Textual t => [t] -> t"},{"n":"Data.Sequences.unwords","t":["Function"],"s":"Textual t => [t] -> t"},{"n":"Data.Sequences.words","t":["Function"],"s":"Textual t => t -> [t]"},{"n":"Control.M
onad.Reader.Class.ask","t":["Function"],"s":"MonadReader r m => m r"},{"n":"Data.Semigroup.<>","t":["Function"],"s":"Semigroup a => a -> a -> a"},{"n":"Data.Semigroup.sconcat","t":["Function"],"s":"Se
migroup a => NonEmpty a -> a"},{"n":"Data.Semigroup.times1p","t":["Function"],"s":"Semigroup a => Natural -> a -> a"},{"n":"Data.Time.Calendar.Days.toModifiedJulianDay","t":["Function"],"s":"Day -> In
teger"},{"n":"Data.Time.Clock.UTC.utctDay","t":["Function"],"s":"UTCTime -> Day"},{"n":"Data.Time.Clock.UTC.utctDayTime","t":["Function"],"s":"UTCTime -> DiffTime"},{"n":"Control.Monad.IO.Class.liftIO
","t":["Function"],"s":"MonadIO m => forall a. IO a -> m a"},{"n":"Control.Monad.Trans.Maybe.runMaybeT","t":["Function"],"s":"MaybeT m a -> m (Maybe a)"},{"n":"Control.Monad.Trans.Reader.runReaderT","
t":["Function"],"s":"ReaderT r m a -> r -> m a"},{"n":"Data.Functor.Identity.runIdentity","t":["Function"],"s":"Identity a -> a"},{"n":"Types.Invoice.bsValue","t":["Function"],"s":"EventKind a -> a"},
{"n":"Types.Invoice.bsName","t":["Function"],"s":"EventKind a -> Text"},{"n":"Types.Invoice.sCfgMinCall","t":["Function"],"s":"UnitAmount -> Double"},{"n":"Types.Invoice.sCfgMinData","t":["Function"],
"s":"UnitAmount -> Double"},{"n":"Types.Invoice.invNumber","t":["Function"],"s":"Invoice -> Text"},{"n":"Types.Invoice.invInterval","t":["Function"],"s":"Invoice -> (Day, Day)"},{"n":"Types.Invoice.in
vClientCode","t":["Function"],"s":"Invoice -> Text"},{"n":"Types.Invoice.invPhone","t":["Function"],"s":"Invoice -> Text"},{"n":"Types.Invoice.invTotal","t":["Function"],"s":"Invoice -> Double"},{"n":
"Types.Invoice.invPlan","t":["Function"],"s":"Invoice -> Text"},{"n":"Types.Invoice.invFees","t":["Function"],"s":"Invoice -> [InvoiceFee]"},{"n":"Types.Invoice.invSections","t":["Function"],"s":"Invo
ice -> [EventKind SummarySection]"},{"n":"Types.Invoice.invFeeName","t":["Function"],"s":"InvoiceFee -> Text"},{"n":"Types.Invoice.invFeeCount","t":["Function"],"s":"InvoiceFee -> Int"},{"n":"Types.In
voice.invFeeTotal","t":["Function"],"s":"InvoiceFee -> Double"},{"n":"Types.Invoice.ssName","t":["Function"],"s":"SummarySection -> Text"},{"n":"Types.Invoice.ssCount","t":["Function"],"s":"SummarySec
tion -> Int"},{"n":"Types.Invoice.ssSpent","t":["Function"],"s":"SummarySection -> Maybe Double"},{"n":"Types.Invoice.ssTotal","t":["Function"],"s":"SummarySection -> Double"},{"n":"Types.Invoice.mkSu
mmarySection","t":["Function"],"s":"[Text] -> Maybe SummarySection"},{"n":"Types.Event.callDateTime","t":["Function"],"s":"Call -> UTCTime"},{"n":"Types.Event.callConnPoint","t":["Function"],"s":"Call
 -> Text"},{"n":"Types.Event.callSpent","t":["Function"],"s":"Call -> Double"},{"n":"Types.Event.smsDateTime","t":["Function"],"s":"Sms -> UTCTime"},{"n":"Types.Event.smsConnPoint","t":["Function"],"s
":"Sms -> Text"},{"n":"Types.Event.dataDateTime","t":["Function"],"s":"Data -> UTCTime"},{"n":"Types.Event.dataConnPoint","t":["Function"],"s":"Data -> Text"},{"n":"Types.Event.dataSpent","t":["Functi
on"],"s":"Data -> Double"},{"n":"Types.Event.unknownText","t":["Function"],"s":"Unknown -> Text"},{"n":"Types.Event.callE","t":["Function"],"s":"Event -> Call"},{"n":"Types.Event.dataE","t":["Function
"],"s":"Event -> Data"},{"n":"Types.Event.smsE","t":["Function"],"s":"Event -> Sms"},{"n":"Types.Event.unknownE","t":["Function"],"s":"Event -> Unknown"},{"n":"Types.Event.eventFilter","t":["Function"
],"s":"IsEvent t => [Event] -> FilteredEv t"},{"n":"Types.Event.eventSort","t":["Function"],"s":"IsEvent t => SortBy -> [t] -> [t]"},{"n":"Types.Event.eventGroup","t":["Function"],"s":"IsEvent t => So
rtBy -> [t] -> [[t]]"},{"n":"Types.Event.toMinAmount","t":["Function"],"s":"IsEvent t => UnitAmount -> t -> Double"},{"n":"Types.Event.getData","t":["Function"],"s":"IsEvent t => t -> (UTCTime, Text, 
Double)"},{"n":"Types.Event.filterCall","t":["Function"],"s":"[Event] -> FilteredEv Call"},{"n":"Types.Event.sortCall","t":["Function"],"s":"SortBy -> [Call] -> [Call]"},{"n":"Types.Event.groupCall","
t":["Function"],"s":"SortBy -> [Call] -> [[Call]]"},{"n":"Types.Event.roundToMinAmount","t":["Function"],"s":"Double -> Double -> Double"},{"n":"Types.Event.filterSms","t":["Function"],"s":"[Event] ->
 FilteredEv Sms"},{"n":"Types.Event.sortSms","t":["Function"],"s":"SortBy -> [Sms] -> [Sms]"},{"n":"Types.Event.groupSms","t":["Function"],"s":"SortBy -> [Sms] -> [[Sms]]"},{"n":"Types.Event.filterDat
a","t":["Function"],"s":"[Event] -> FilteredEv Data"},{"n":"Types.Event.sortData","t":["Function"],"s":"SortBy -> [Data] -> [Data]"},{"n":"Types.Event.groupData","t":["Function"],"s":"SortBy -> [Data]
 -> [[Data]]"},{"n":"Types.Event.filterUnknown","t":["Function"],"s":"[Event] -> FilteredEv Unknown"},{"n":"Types.Event.sortUnknown","t":["Function"],"s":"SortBy -> [Unknown] -> [Unknown]"},{"n":"Type
s.Event.groupUnknown","t":["Function"],"s":"SortBy -> [Unknown] -> [[Unknown]]"}],[]]

Error log:
!SESSION 2015-03-09 09:51:45.194 -----------------------------------------------
eclipse.buildId=4.3.2.M20140221-1700
java.version=1.7.0_76
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=hr_HR
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.standard.product

!ENTRY net.sf.eclipsefp.haskell.buildwrapper 4 4 2015-03-09 09:52:35.618
!MESSAGE Error while launching buildwrapper process
!STACK 0
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.readLine(BufferedReader.java:317)
	at java.io.BufferedReader.readLine(BufferedReader.java:382)
	at net.sf.eclipsefp.haskell.buildwrapper.BWFacade.readArrayBW(BWFacade.java:594)
	at net.sf.eclipsefp.haskell.buildwrapper.BWFacade.build1LongRunning(BWFacade.java:498)
	at net.sf.eclipsefp.haskell.buildwrapper.JobFacade$5$1.run(JobFacade.java:357)
	at net.sf.eclipsefp.haskell.buildwrapper.BWFacade.waitForThread(BWFacade.java:1898)
	at net.sf.eclipsefp.haskell.buildwrapper.BWFacade.waitForThread(BWFacade.java:1836)
	at net.sf.eclipsefp.haskell.buildwrapper.JobFacade$5.run(JobFacade.java:371)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
!SESSION 2015-03-09 09:52:42.195 -----------------------------------------------
eclipse.buildId=4.3.2.M20140221-1700
java.version=1.7.0_76
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=hr_HR
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.standard.product

!ENTRY org.eclipse.core.resources 2 10035 2015-03-09 09:52:44.536
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

**Comment by JPMoresmau** [comment]
The build1LongRunning operation seems to have caused BuildWrapper to crash. Maybe rebuild it with -dynamic. Of course if something causes BuildWrapper to crash, every time it has to respawn and then crash again, so that will cause the lag. Probable causes of crashing are something to do with dynamic-cabal or not using the -dynamic flag to build BuildWrapper (flag which maybe should be passed by default, but I'm far from sure -dynamic works everywhere in all cases either).

**Comment by vlatkoB** [comment]
I had BW 0.9 and it was build with -dynamic. Must build it with -dynamic, otherwise doesn't work properly (forgot what exactly). I built BW 0.9.2 from git, and now things look much better. There is still slowness, but not something I'd rant about. No more errors in Eclipse log.

I'll try it for some more time before closing the issue.

**Comment by EvgenyNerush** [comment]
I had the same issue as apriori, also on Arch Linux. The solution (for me) is to install ghc and cabal-install from the [haskell-core] repository (https://wiki.archlinux.org/index.php/ArchHaskell).

**Comment by apriori** [comment]
@EvgenyNerush: Thank you very much. That pretty much fixed my issue as well. Although I prefer to understand what the underlying issue actually was.
Unfortunately even with the "fix" the responsiveness of typing is nowhere even close to that of e.g. Leksah (and yeah, I know leksah lacks a lot).
