### ISSUE TITLE
Eclipse hangs for several seconds when typing and buildwrapper failure

### ISSUE THREAD

**Issue by jens-auer** [JPMoresmau/eclipsefp#291]
Hi,

I have a fresh install of Ubuntu 15.10 with haskell-platform, a minimal eclipse and EclipseFP from the update site. I created a sample project, but when edit a haskell file, every key stroke will take a couple of seconds to evaluate. I can see buildwrapper and cabal processes running while the system is stalled. When finished, no buildwrapper or cabal are running anymore.

The debug console does not show any problems I am aware of:
```
Resolving dependencies...
Configuring xvsv-0.1...
/home/jens/.cabal/bin/buildwrapper getbuildflags --file=src/Main.hs --tempfolder=.dist-buildwrapper --cabalpath=/usr/bin/cabal --cabalfile=/home/jens/workspace/xvsv/xvsv.cabal --cabalflags= --cabaloption=--with-
ghc=/usr/bin/ghc --logcabal=true
configuring because setup_config not present
/usr/bin/cabal configure '--verbose=1' --enable-tests --enable-benchmarks '--builddir=/home/jens/workspace/xvsv/.dist-buildwrapper/dist' '--with-ghc=/usr/bin/ghc' --user
Resolving dependencies...
Configuring xvsv-0.1...
/home/jens/.cabal/bin/buildwrapper getbuildflags --file=src/Main.hs --tempfolder=.dist-buildwrapper --cabalpath=/usr/bin/cabal --cabalfile=/home/jens/workspace/xvsv/xvsv.cabal --cabalflags= --cabaloption=--with-
ghc=/usr/bin/ghc --logcabal=true
configuring because setup_config not present
/usr/bin/cabal configure '--verbose=1' --enable-tests --enable-benchmarks '--builddir=/home/jens/workspace/xvsv/.dist-buildwrapper/dist' '--with-ghc=/usr/bin/ghc' --user
Resolving dependencies...
Configuring xvsv-0.1...
/home/jens/.cabal/bin/buildwrapper tokentypes --file=src/Main.hs --tempfolder=.dist-buildwrapper --cabalpath=/usr/bin/cabal --cabalfile=/home/jens/workspace/xvsv/xvsv.cabal --cabalflags= --cabaloption=--with-ghc
=/usr/bin/ghc --logcabal=true
build-wrapper-json:[[{"K":[1,1,7]},{"IC":[1,8,12]},{"K":[1,13,18]},{"IV":[2,1]},{"IV":[3,1,5]},{"S":[3,5,7]},{"IC":[3,7,9]},{"SS":[3,9]},{"SS":[3,10]},{"IV":[4,1,5]},{"S":[4,6]},{"IV":[4,8,17]}],[]]
/home/jens/.cabal/bin/buildwrapper getbuildflags --file=src/Main.hs --tempfolder=.dist-buildwrapper --cabalpath=/usr/bin/cabal --cabalfile=/home/jens/workspace/xvsv/xvsv.cabal --cabalflags= --cabaloption=--with-
ghc=/usr/bin/ghc --logcabal=true
configuring because setup_config not present
/usr/bin/cabal configure '--verbose=1' --enable-tests --enable-benchmarks '--builddir=/home/jens/workspace/xvsv/.dist-buildwrapper/dist' '--with-ghc=/usr/bin/ghc' --user
Resolving dependencies...
Configuring xvsv-0.1...
/home/jens/.cabal/bin/buildwrapper getbuildflags --file=src/Main.hs --tempfolder=.dist-buildwrapper --cabalpath=/usr/bin/cabal --cabalfile=/home/jens/workspace/xvsv/xvsv.cabal --cabalflags= --cabaloption=--with-
ghc=/usr/bin/ghc --logcabal=true
configuring because setup_config not present
/usr/bin/cabal configure '--verbose=1' --enable-tests --enable-benchmarks '--builddir=/home/jens/workspace/xvsv/.dist-buildwrapper/dist' '--with-ghc=/usr/bin/ghc' --user
Resolving dependencies...
Configuring xvsv-0.1...
/home/jens/.cabal/bin/buildwrapper tokentypes --file=src/Main.hs --tempfolder=.dist-buildwrapper --cabalpath=/usr/bin/cabal --cabalfile=/home/jens/workspace/xvsv/xvsv.cabal --cabalflags= --cabaloption=--with-ghc
=/usr/bin/ghc --logcabal=true
build-wrapper-json:[[{"K":[1,1,7]},{"IC":[1,8,12]},{"K":[1,13,18]},{"IV":[2,1]},{"IV":[3,1,5]},{"S":[3,5,7]},{"IC":[3,7,9]},{"SS":[3,9]},{"SS":[3,10]},{"IV":[4,1,5]},{"S":[4,6]},{"IV":[4,8,17]}],[]]
/home/jens/.cabal/bin/buildwrapper getbuildflags --file=src/Main.hs --tempfolder=.dist-buildwrapper --cabalpath=/usr/bin/cabal --cabalfile=/home/jens/workspace/xvsv/xvsv.cabal --cabalflags= --cabaloption=--with-
ghc=/usr/bin/ghc --logcabal=true
configuring because setup_config not present
/usr/bin/cabal configure '--verbose=1' --enable-tests --enable-benchmarks '--builddir=/home/jens/workspace/xvsv/.dist-buildwrapper/dist' '--with-ghc=/usr/bin/ghc' --user
Resolving dependencies...
Configuring xvsv-0.1...
/home/jens/.cabal/bin/buildwrapper outline --file=src/Main.hs --tempfolder=.dist-buildwrapper --cabalpath=/usr/bin/cabal --cabalfile=/home/jens/workspace/xvsv/xvsv.cabal --cabalflags= --cabaloption=--with-ghc=/u
sr/bin/ghc --logcabal=true
configuring because setup_config not present
/usr/bin/cabal configure '--verbose=1' --enable-tests --enable-benchmarks '--builddir=/home/jens/workspace/xvsv/.dist-buildwrapper/dist' '--with-ghc=/usr/bin/ghc' --user
Resolving dependencies...
Configuring xvsv-0.1...
/home/jens/.cabal/bin/buildwrapper getbuildflags --file=src/Main.hs --tempfolder=.dist-buildwrapper --cabalpath=/usr/bin/cabal --cabalfile=/home/jens/workspace/xvsv/xvsv.cabal --cabalflags= --cabaloption=--with-
ghc=/usr/bin/ghc --logcabal=true
configuring because setup_config not present
/usr/bin/cabal configure '--verbose=1' --enable-tests --enable-benchmarks '--builddir=/home/jens/workspace/xvsv/.dist-buildwrapper/dist' '--with-ghc=/usr/bin/ghc' --user
Resolving dependencies...
Configuring xvsv-0.1...
```

The Eclipse log also usually does not show any problems, but I was able to sport a buildwrapper crash:
```
!ENTRY net.sf.eclipsefp.haskell.buildwrapper 4 4 2015-11-10 23:22:05.796
!MESSAGE Error while launching buildwrapper process
!STACK 0
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at net.sf.eclipsefp.haskell.buildwrapper.BWFacade.getThingAtPoint(BWFacade.java:1174)
	at net.sf.eclipsefp.haskell.ui.internal.editors.haskell.HaskellTextHover.computeThingAtPoint(HaskellTextHover.java:190)
	at net.sf.eclipsefp.haskell.ui.internal.editors.haskell.HaskellTextHover.getHoverInfo2(HaskellTextHover.java:80)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:166)
```

 However, this does not usually happen when the system stalls.

Right now, EclipseFP is not usable for me, so I would really appreciate any help.

I am running Ubuntu 15.10, ghc 7.8.4, buildwrapper-0.9.1, cabal 1.22.1.1. I have reinstalled buildwrapper with the dynamic flag as suggested in issue #290, but without any improvement.

Best wishes,
  Jens
Best wishes,
  Jens

**Comment by jens-auer** [comment]
Any idea what is causing this? I have a delay of more than 10s between key strokes. I would really like to use EclipseFP, but as it is now it doesn't make sense.
